### ISSUE TITLE
Question about Collecting data from the simulator

### ISSUE THREAD

**Issue by qhxxsb** [kpandey008/carla-aebs#2]
Hi,
When I try to the $python collect.py, I met the problem which is shown that "RuntimeError: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed." And then, the destination folder only is generated one episode. How could I fix up the problem?

**Comment by kpandey008** [comment]
If you can mention the exact steps you used to run the script, I can help further. Did you run the Carla simulator first before running the script?

**Comment by qhxxsb** [comment]
Hi ,
Many thanks for your reply. Of course, I run the Carla as serve first, I mean the collect.py can work, but it can only work once.
According to the hyperparameters, --num-episodes 80 , which means that it will have 80 episodes folder, but now it  only generates one folder called [episode_1.]
After that, it shows "RuntimeError: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed."
Many thanks for your help again!

> If you can mention the exact steps you used to run the script, I can help further. Did you run the Carla simulator first before running the script?

**Comment by qhxxsb** [comment]
Hi again,
I guess I found the problem, in world.py 242line, note the function destroy_actors().
Then it goes to work. Although I cannot understand why should destroy the actors. Hope my modification is correct.

**Comment by kpandey008** [comment]
@qhxxsb I fixed the problem. Check https://github.com/kpandey008/carla-aebs/commit/649f230d35b1f161705c5f3511b552f2cc7debd8 for the fix. Basically, there was a bug in the collect.py script itself. You can pull from the master to incorporate the changes locally. I have tested it locally and it works now. Thanks for raising the issue!
Closing this. Re-open if the problem persists.
